// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuPVkvM8VK0uY51ih0QrjP1V5F-JBYWPU',
    appId: '1:952579980315:web:9084958ee9e4e1c4f78cbe',
    messagingSenderId: '952579980315',
    projectId: 'unishare-e9d52',
    authDomain: 'unishare-e9d52.firebaseapp.com',
    storageBucket: 'unishare-e9d52.appspot.com',
    measurementId: 'G-6RK71VVSLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzRITabuLqpqkA6LYOn1l_eOzbsrw9hs',
    appId: '1:952579980315:android:289659bfbdc7ebbff78cbe',
    messagingSenderId: '952579980315',
    projectId: 'unishare-e9d52',
    storageBucket: 'unishare-e9d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB20qdGO2_ptXDBgv3KwxH26EAo3mjFc9E',
    appId: '1:952579980315:ios:816b8aae37f58d97f78cbe',
    messagingSenderId: '952579980315',
    projectId: 'unishare-e9d52',
    storageBucket: 'unishare-e9d52.appspot.com',
    iosBundleId: 'com.example.uniShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB20qdGO2_ptXDBgv3KwxH26EAo3mjFc9E',
    appId: '1:952579980315:ios:816b8aae37f58d97f78cbe',
    messagingSenderId: '952579980315',
    projectId: 'unishare-e9d52',
    storageBucket: 'unishare-e9d52.appspot.com',
    iosBundleId: 'com.example.uniShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuPVkvM8VK0uY51ih0QrjP1V5F-JBYWPU',
    appId: '1:952579980315:web:1f47a0f40ec5fe00f78cbe',
    messagingSenderId: '952579980315',
    projectId: 'unishare-e9d52',
    authDomain: 'unishare-e9d52.firebaseapp.com',
    storageBucket: 'unishare-e9d52.appspot.com',
    measurementId: 'G-FGW43TZKCL',
  );

}